source 'https://rubygems.org'

gem 'r10k', '~>2.0'
gem 'hiera', '~>3.0'
gem 'hiera-eyaml', '~>2.0'
gem 'facter', '~>2.4'
gem 'puppet', '~>4.3'

gem 'puppetlabs_spec_helper', '~>0.10.3'
gem 'puppet-lint', '~>1.0'

gem 'puppet-lint-variable_contains_upcase'
gem 'puppet-lint-absolute_template_path'
gem 'puppet-lint-strict_indent-check'
gem 'puppet-lint-unquoted_string-check'
gem 'puppet-lint-empty_string-check'
gem 'puppet-lint-spaceship_operator_without_tag-check'
gem 'puppet-lint-absolute_classname-check'
gem 'puppet-lint-undef_in_function-check'
gem 'puppet-lint-leading_zero-check'
gem 'puppet-lint-numericvariable'
gem 'puppet-lint-file_ensure-check'
gem 'puppet-lint-trailing_comma-check'
gem 'puppet-lint-version_comparison-check'
gem 'puppet-lint-global_resource-check'
gem 'puppet-lint-appends-check'
gem 'puppet-lint-classes_and_types_beginning_with_digits--check'
gem 'puppet-lint-fileserver-check'
gem 'puppet-lint-resource_outside_class-check'
gem 'puppet-lint-alias-check'
